hot fix: adding checks for trailing whitespace and tabs in CI
 required for slaclab/surf's CI

diff --git a/.github/workflows/ruckus_ci.yml b/.github/workflows/ruckus_ci.yml
--- a/.github/workflows/ruckus_ci.yml
+++ b/.github/workflows/ruckus_ci.yml
@@ -38,6 +38,20 @@ jobs:
           python -m pip install --upgrade pip
           pip install flake8
 
+      - name: Check for trailing whitespace and tabs
+        run: |
+          # Check for trailing whitespace
+          if grep -rnI '[[:blank:]]$' --include=\*.{tcl,py,sh} .; then
+            echo "Error: Trailing whitespace found in the repository!"
+            exit 1
+          fi
+
+          # Check for tab characters instead of spaces
+          if grep -rnI $'\t' --include=\*.{tcl,py,sh} .; then
+            echo "Error: Tab characters found in the repository! Please use spaces for indentation."
+            exit 1
+          fi
+
       - name: Python Syntax Check
         run: |
           python -m compileall -f scripts/
